/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsTapRouteImport } from './routes/tools.tap'
import { Route as ToolsSosRouteImport } from './routes/tools.sos'
import { Route as ToolsMemoryRouteImport } from './routes/tools.memory'
import { Route as ToolsColdRouteImport } from './routes/tools.cold'
import { Route as ToolsBreathRouteImport } from './routes/tools.breath'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTapRoute = ToolsTapRouteImport.update({
  id: '/tap',
  path: '/tap',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSosRoute = ToolsSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMemoryRoute = ToolsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsColdRoute = ToolsColdRouteImport.update({
  id: '/cold',
  path: '/cold',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBreathRoute = ToolsBreathRouteImport.update({
  id: '/breath',
  path: '/breath',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tree': typeof TreeRoute
  '/tools/breath': typeof ToolsBreathRoute
  '/tools/cold': typeof ToolsColdRoute
  '/tools/memory': typeof ToolsMemoryRoute
  '/tools/sos': typeof ToolsSosRoute
  '/tools/tap': typeof ToolsTapRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tree': typeof TreeRoute
  '/tools/breath': typeof ToolsBreathRoute
  '/tools/cold': typeof ToolsColdRoute
  '/tools/memory': typeof ToolsMemoryRoute
  '/tools/sos': typeof ToolsSosRoute
  '/tools/tap': typeof ToolsTapRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/community': typeof CommunityRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tree': typeof TreeRoute
  '/tools/breath': typeof ToolsBreathRoute
  '/tools/cold': typeof ToolsColdRoute
  '/tools/memory': typeof ToolsMemoryRoute
  '/tools/sos': typeof ToolsSosRoute
  '/tools/tap': typeof ToolsTapRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/challenges'
    | '/community'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/tools'
    | '/tree'
    | '/tools/breath'
    | '/tools/cold'
    | '/tools/memory'
    | '/tools/sos'
    | '/tools/tap'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/challenges'
    | '/community'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/tree'
    | '/tools/breath'
    | '/tools/cold'
    | '/tools/memory'
    | '/tools/sos'
    | '/tools/tap'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/challenges'
    | '/community'
    | '/onboarding'
    | '/paywall'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/tools'
    | '/tree'
    | '/tools/breath'
    | '/tools/cold'
    | '/tools/memory'
    | '/tools/sos'
    | '/tools/tap'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  CommunityRoute: typeof CommunityRoute
  OnboardingRoute: typeof OnboardingRoute
  PaywallRoute: typeof PaywallRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  TreeRoute: typeof TreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tap': {
      id: '/tools/tap'
      path: '/tap'
      fullPath: '/tools/tap'
      preLoaderRoute: typeof ToolsTapRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/sos': {
      id: '/tools/sos'
      path: '/sos'
      fullPath: '/tools/sos'
      preLoaderRoute: typeof ToolsSosRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/memory': {
      id: '/tools/memory'
      path: '/memory'
      fullPath: '/tools/memory'
      preLoaderRoute: typeof ToolsMemoryRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/cold': {
      id: '/tools/cold'
      path: '/cold'
      fullPath: '/tools/cold'
      preLoaderRoute: typeof ToolsColdRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/breath': {
      id: '/tools/breath'
      path: '/breath'
      fullPath: '/tools/breath'
      preLoaderRoute: typeof ToolsBreathRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsBreathRoute: typeof ToolsBreathRoute
  ToolsColdRoute: typeof ToolsColdRoute
  ToolsMemoryRoute: typeof ToolsMemoryRoute
  ToolsSosRoute: typeof ToolsSosRoute
  ToolsTapRoute: typeof ToolsTapRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsBreathRoute: ToolsBreathRoute,
  ToolsColdRoute: ToolsColdRoute,
  ToolsMemoryRoute: ToolsMemoryRoute,
  ToolsSosRoute: ToolsSosRoute,
  ToolsTapRoute: ToolsTapRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  CommunityRoute: CommunityRoute,
  OnboardingRoute: OnboardingRoute,
  PaywallRoute: PaywallRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  TreeRoute: TreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
